module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      ['feat', 'fix', 'docs', 'style', 'refactor', 'test', 'chore', 'perf', 'ci', 'revert'],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'core',
        'repo',
        'docs',
        'auth',
        'gateway',
        'hr',
        'payroll',
        'leave',
        'appraisal',
        'notification',
        'subscription',
        'marketing',
        'operations',
        'reinsurance',
        'web',
        'types',
        'schemas',
        'utils',
        'config',
        'infra',
        'deps',
        'release',
        'ci',
        'security',
        'accounting',
      ],
    ],
    'subject-max-length': [2, 'always', 100],
  },
};
