import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import {
  IsArray,
  IsBoolean,
  IsDateString,
  IsNotEmpty,
  IsNotEmptyObject,
  IsNumber,
  IsOptional,
  IsString,
  IsUUID,
  Max,
  MaxLength,
  Min,
  ValidateNested,
} from 'class-validator';
import { CollapseWhitespaceString } from '../../crm-settings/dto/string.transforms';
import { ClientBillingDto } from './billing.dto';
import {
  CreateProspectContactDto,
  CreateProspectLocationDto,
} from '../../prospects/dto/create-prospect.dto';

export class CreateClientDto {
  @ApiPropertyOptional({
    format: 'uuid',
    description:
      'User to assign it to. Defaults to the creator; choosing someone else needs the assign permission.',
  })
  @IsOptional()
  @IsUUID()
  assignedUserId?: string;
  @ApiPropertyOptional({
    format: 'uuid',
    description:
      'Generated by the caller so a retry after a failure reuses the same client (and the same Accounting entity) instead of creating another.',
  })
  @IsOptional()
  @IsUUID()
  id?: string;

  @ApiProperty({ example: 'Acme Manufacturing Ltd', maxLength: 200 })
  @CollapseWhitespaceString()
  @IsString()
  @IsNotEmpty()
  @MaxLength(200)
  companyName!: string;

  @ApiPropertyOptional({
    example: '5f01c5e7-4f1b-4e47-9b69-8ecf18bc6585',
    description: 'CRM Settings business type ID.',
  })
  @IsOptional()
  @IsUUID()
  businessTypeId?: string;

  @ApiPropertyOptional({
    example: '5f01c5e7-4f1b-4e47-9b69-8ecf18bc6585',
    description: 'CRM Settings source type ID.',
  })
  @IsOptional()
  @IsUUID()
  sourceTypeId?: string;

  @ApiPropertyOptional({
    default: false,
    description:
      'A billable client must come with its first billing transaction, which is sent to Accounting.',
  })
  @IsOptional()
  @IsBoolean()
  isBillable?: boolean;

  @ApiPropertyOptional({ type: ClientBillingDto })
  @IsOptional()
  @ValidateNested()
  @Type(() => ClientBillingDto)
  billing?: ClientBillingDto;

  @ApiProperty({ type: CreateProspectContactDto })
  @IsNotEmptyObject()
  @ValidateNested()
  @Type(() => CreateProspectContactDto)
  primaryContact!: CreateProspectContactDto;

  @ApiPropertyOptional({
    type: [String],
    description:
      'CRM Settings product/service IDs the client is linked to. Each starts as PENDING.',
  })
  @IsOptional()
  @IsArray()
  @IsUUID('all', { each: true })
  productIds?: string[];

  @ApiPropertyOptional({
    type: () => [AddClientProductDto],
    description:
      'Products/services with their expected revenue, commission rate and expected close date. Use this or productIds, not both.',
  })
  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => AddClientProductDto)
  products?: AddClientProductDto[];

  @ApiProperty({ type: CreateProspectLocationDto })
  @IsNotEmptyObject()
  @ValidateNested()
  @Type(() => CreateProspectLocationDto)
  location!: CreateProspectLocationDto;
}

export class ConvertProspectToClientDto {
  @ApiPropertyOptional({
    format: 'uuid',
    description:
      'Generated by the caller so a retry reuses the same client and Accounting entity.',
  })
  @IsOptional()
  @IsUUID()
  clientId?: string;

  @ApiPropertyOptional({
    default: false,
    description:
      'Marks the new client as billable. Requires the first billing transaction.',
  })
  @IsOptional()
  @IsBoolean()
  isBillable?: boolean;

  @ApiPropertyOptional({ type: ClientBillingDto })
  @IsOptional()
  @ValidateNested()
  @Type(() => ClientBillingDto)
  billing?: ClientBillingDto;
}

export class AddClientProductDto {
  @ApiProperty({
    example: '5f01c5e7-4f1b-4e47-9b69-8ecf18bc6585',
    description: 'CRM Settings product/service option ID.',
  })
  @IsUUID()
  productId!: string;

  @ApiPropertyOptional({ example: 10000, minimum: 0 })
  @IsOptional()
  @Type(() => Number)
  @IsNumber({ maxDecimalPlaces: 2 })
  @Min(0)
  expectedValue?: number;

  @ApiPropertyOptional({
    example: 10,
    minimum: 0,
    maximum: 100,
    description:
      'Percentage of the expected value. The commission amount is derived from it.',
  })
  @IsOptional()
  @Type(() => Number)
  @IsNumber({ maxDecimalPlaces: 4 })
  @Min(0)
  @Max(100)
  commissionRate?: number;

  @ApiPropertyOptional({ example: '2026-10-31' })
  @IsOptional()
  @IsDateString()
  expectedCloseDate?: string;
}
