export const AccountingPermission = {
  SETTINGS_VIEW: 'accounting.settings:VIEW',
  SETTINGS_EDIT: 'accounting.settings:EDIT',
  ACCOUNTS_VIEW: 'accounting.accounts:VIEW',
  ACCOUNTS_CREATE: 'accounting.accounts:CREATE',
  ACCOUNTS_EDIT: 'accounting.accounts:EDIT',
  CUSTOMERS_VIEW: 'accounting.customers:VIEW',
  CUSTOMERS_CREATE: 'accounting.customers:CREATE',
  CUSTOMERS_EDIT: 'accounting.customers:EDIT',
  CUSTOMERS_DEACTIVATE: 'accounting.customers:DEACTIVATE',
  VENDORS_VIEW: 'accounting.vendors:VIEW',
  VENDORS_CREATE: 'accounting.vendors:CREATE',
  VENDORS_EDIT: 'accounting.vendors:EDIT',
  VENDORS_DEACTIVATE: 'accounting.vendors:DEACTIVATE',
  JOURNALS_VIEW: 'accounting.journals:VIEW',
  JOURNALS_CREATE: 'accounting.journals:CREATE',
  JOURNALS_EDIT: 'accounting.journals:EDIT',
  JOURNALS_POST: 'accounting.journals:APPROVE',
  LEDGER_VIEW: 'accounting.ledger:VIEW',
} as const;
