export const AccountingPermission = {
  SETTINGS_VIEW: 'accounting.settings:VIEW',
  SETTINGS_EDIT: 'accounting.settings:EDIT',
  ACCOUNTS_VIEW: 'accounting.accounts:VIEW',
  ACCOUNTS_CREATE: 'accounting.accounts:CREATE',
  ACCOUNTS_EDIT: 'accounting.accounts:EDIT',
  ACCOUNT_CLASSIFICATIONS_VIEW: 'accounting.account-classifications:VIEW',
  ACCOUNT_CLASSIFICATIONS_CREATE: 'accounting.account-classifications:CREATE',
  ACCOUNT_CLASSIFICATIONS_EDIT: 'accounting.account-classifications:EDIT',
  ACCOUNT_CLASSIFICATIONS_DEACTIVATE:
    'accounting.account-classifications:DEACTIVATE',
  ACCOUNT_GROUPS_VIEW: 'accounting.account-groups:VIEW',
  ACCOUNT_GROUPS_CREATE: 'accounting.account-groups:CREATE',
  ACCOUNT_GROUPS_EDIT: 'accounting.account-groups:EDIT',
  ACCOUNT_GROUPS_DEACTIVATE: 'accounting.account-groups:DEACTIVATE',
  CUSTOMERS_VIEW: 'accounting.customers:VIEW',
  CUSTOMERS_CREATE: 'accounting.customers:CREATE',
  CUSTOMERS_EDIT: 'accounting.customers:EDIT',
  CUSTOMERS_DEACTIVATE: 'accounting.customers:DEACTIVATE',
  VENDORS_VIEW: 'accounting.vendors:VIEW',
  VENDORS_CREATE: 'accounting.vendors:CREATE',
  VENDORS_EDIT: 'accounting.vendors:EDIT',
  VENDORS_DEACTIVATE: 'accounting.vendors:DEACTIVATE',
  CASH_ACCOUNTS_VIEW: 'accounting.cash-accounts:VIEW',
  CASH_ACCOUNTS_MANAGE: 'accounting.cash-accounts:EDIT',
  CASHBOOK_VIEW: 'accounting.cashbook:VIEW',
  CASHBOOK_CREATE: 'accounting.cashbook:CREATE',
  CASHBOOK_POST: 'accounting.cashbook:APPROVE',
  CASHBOOK_REVERSE: 'accounting.cashbook:DELETE',
  BANK_RECONCILIATIONS_VIEW: 'accounting.bank-reconciliations:VIEW',
  BANK_RECONCILIATIONS_MANAGE: 'accounting.bank-reconciliations:EDIT',
  RECEIVABLES_VIEW: 'accounting.receivables:VIEW',
  RECEIVABLES_CREATE: 'accounting.receivables:CREATE',
  RECEIVABLES_POST: 'accounting.receivables:APPROVE',
  RECEIVABLES_REVERSE: 'accounting.receivables:DELETE',
  RECEIVABLES_ALLOCATE: 'accounting.receivables:EDIT',
  PAYABLES_VIEW: 'accounting.payables:VIEW',
  PAYABLES_CREATE: 'accounting.payables:CREATE',
  PAYABLES_POST: 'accounting.payables:APPROVE',
  PAYABLES_REVERSE: 'accounting.payables:DELETE',
  PAYABLES_ALLOCATE: 'accounting.payables:EDIT',
  JOURNALS_VIEW: 'accounting.journals:VIEW',
  JOURNALS_CREATE: 'accounting.journals:CREATE',
  JOURNALS_EDIT: 'accounting.journals:EDIT',
  JOURNALS_POST: 'accounting.journals:APPROVE',
  LEDGER_VIEW: 'accounting.ledger:VIEW',
} as const;
