ALTER TYPE notify."NotificationType" ADD VALUE IF NOT EXISTS 'SHIFT_SWAP_REQUESTED';
ALTER TYPE notify."NotificationType" ADD VALUE IF NOT EXISTS 'SHIFT_SWAP_PENDING_MANAGER';
ALTER TYPE notify."NotificationType" ADD VALUE IF NOT EXISTS 'SHIFT_SWAP_DECLINED';
ALTER TYPE notify."NotificationType" ADD VALUE IF NOT EXISTS 'SHIFT_SWAP_APPROVED';
ALTER TYPE notify."NotificationType" ADD VALUE IF NOT EXISTS 'SHIFT_SWAP_REJECTED';
ALTER TYPE notify."NotificationType" ADD VALUE IF NOT EXISTS 'SHIFT_SWAP_EXPIRED';
