services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: erp-rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: erp
      RABBITMQ_DEFAULT_PASS: erppassword
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: erp-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  api-gateway:
    image: ghcr.io/datrix-tech-solutions/work-phelo/api-gateway:dev
    container_name: erp-gateway-dev
    restart: unless-stopped
    ports:
      - '4010:4000'
    env_file:
      - ../apps/api-gateway/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

  auth-service:
    image: ghcr.io/datrix-tech-solutions/work-phelo/auth-service:dev
    container_name: erp-auth-dev
    restart: unless-stopped
    ports:
      - '4001:4001'
    env_file:
      - ../apps/auth-service/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

  hr-service:
    image: ghcr.io/datrix-tech-solutions/work-phelo/hr-service:dev
    container_name: erp-hr-dev
    restart: unless-stopped
    ports:
      - '4002:4002'
    env_file:
      - ../apps/hr-service/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

  notification-service:
    image: ghcr.io/datrix-tech-solutions/work-phelo/notification-service:dev
    container_name: erp-notification-dev
    restart: unless-stopped
    ports:
      - '4004:4004'
    env_file:
      - ../apps/notification-service/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

  subscription-service:
    image: ghcr.io/datrix-tech-solutions/work-phelo/subscription-service:dev
    container_name: erp-subscription-dev
    restart: unless-stopped
    ports:
      - '4005:4005'
    env_file:
      - ../apps/subscription-service/.env
    depends_on:
      rabbitmq:
        condition: service_healthy

  marketing-service:
    image: ghcr.io/datrix-tech-solutions/work-phelo/marketing-service:dev
    container_name: erp-marketing-dev
    restart: unless-stopped
    ports:
      - '4006:4006'
    env_file:
      - ../apps/marketing-service/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  rabbitmq_data:
  redis_data:
